"""full phone number

Revision ID: 17b9a3f713fd
Revises: bea54f7fa062
Create Date: 2020-06-23 08:50:38.228141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b9a3f713fd'
down_revision = 'bea54f7fa062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_phone_number', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'full_phone_number')
    # ### end Alembic commands ###
