"""Added verification details

Revision ID: 50ee7edb7d31
Revises: e44d1eff1cf4
Create Date: 2020-02-09 23:31:05.399199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ee7edb7d31'
down_revision = 'e44d1eff1cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verified_at')
    # ### end Alembic commands ###
