"""effective_at field

Revision ID: 6ce7dde88ddb
Revises: 2b8feb746dca
Create Date: 2020-06-27 09:29:07.996583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce7dde88ddb'
down_revision = '2b8feb746dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_transaction', sa.Column('effective_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_transaction', 'effective_at')
    # ### end Alembic commands ###
